/**
 * Constants application
 *
**/

module.exports.constants = {
    response: {
      RECHARGE_CREATED_SUCCESS: "RECHARGE_CREATED_SUCCESS",
      EXPENSE_CREATED_SUCCESS: "RECHARGE_CREATED_SUCCESS",
      CUSTOMER_UPDATE_ERROR: "CUSTOMER_UPDATE_ERROR",
      UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
      CLIENT_IS_NOT_CREATED : "CLIENT_IS_NOT_CREATED",
      BALANCE_RESPONSE_SUCCESS: "BALANCE_RESPONSE_SUCCESS",
      EXPENSE_RESPONSE_SUCCESS: "BALANCE_RESPONSE_SUCCESS",
      COST_CREATE_SUCCESS: "COST_CREATE_SUCCESS",
      COST_REQUIRED_SUCCESS: "COST_REQUIRED_SUCCESS",
      COST_UPDATED_SUCCESS: "COST_UPDATED_SUCCESS"

    }
};
